In [19]:
import tensorflow as tf

# tf.constant and Creating tensors

In [30]:
tf.constant?

Signature: tf.constant(value, dtype=None, shape=None, name='Const')
Docstring:
Creates a constant tensor from a tensor-like object.

Note: All eager `tf.Tensor` values are immutable (in contrast to
`tf.Variable`). There is nothing especially _constant_ about the value
returned from `tf.constant`. This function is not fundamentally different from
`tf.convert_to_tensor`. The name `tf.constant` comes from the `value` being
embedded in a `Const` node in the `tf.Graph`. `tf.constant` is useful
for asserting that the value can be embedded that way.

If the argument `dtype` is not specified, then the type is inferred from
the type of `value`.

>>> # Constant 1-D Tensor from a python list.
>>> tf.constant([1, 2, 3, 4, 5, 6])
<tf.Tensor: shape=(6,), dtype=int32,
    numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
>>> # Or a numpy array
>>> a = np.array([[1, 2, 3], [4, 5, 6]])
>>> tf.constant(a)
<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
  array([[1, 2, 3],
         [4, 5, 6]])>

If `dtype` is 

In [20]:
scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [21]:
vector = tf.constant([10,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>

In [22]:
matrix = tf.constant([[10,4],
                     [11,3]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [11,  3]], dtype=int32)>

In [23]:
tensor = tf.constant([[[10,4],[11,3]],
                      [[11,2],[11,4]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[10,  4],
        [11,  3]],

       [[11,  2],
        [11,  4]]], dtype=int32)>

In [24]:
scaler.ndim

0

In [25]:
vector.ndim

1

In [26]:
matrix.ndim

2

In [27]:
tensor.ndim

3

# tf.variables and Creating tensors

In [29]:
tf.Variable?

Init signature: tf.Variable(*args, **kwargs)
Docstring:     
See the [variable guide](https://tensorflow.org/guide/variable).

A variable maintains shared, persistent state manipulated by a program.

The `Variable()` constructor requires an initial value for the variable, which
can be a `Tensor` of any type and shape. This initial value defines the type
and shape of the variable. After construction, the type and shape of the
variable are fixed. The value can be changed using one of the assign methods.

>>> v = tf.Variable(1.)
>>> v.assign(2.)
<tf.Variable ... shape=() dtype=float32, numpy=2.0>
>>> v.assign_add(0.5)
<tf.Variable ... shape=() dtype=float32, numpy=2.5>

The `shape` argument to `Variable`'s constructor allows you to construct a
variable with a less defined shape than its `initial_value`:

>>> v = tf.Variable(1., shape=tf.TensorShape(None))
>>> v.assign([[1.]])
<tf.Variable ... shape=<unknown> dtype=float32, numpy=array([[1.]], ...)>

Just like any `Tensor`, variables creat